<a href="https://colab.research.google.com/github/uthfol-sust/DL-Lab-Course/blob/main/Neuron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score

In [2]:
def Sigmoid(x):
    return 1/(1+np.exp(-x))

def Sigmoid_derivative(x):
    s = Sigmoid(x)
    return s*(1-s)

In [3]:
class Perceptron:

    def __init__(self, learning_rate=0.01, n_iter=100):
        self.lr = learning_rate
        self.n_iter = n_iter

    def fit(self, X, y):

        X = np.asarray(X, dtype=np.float64)
        y = np.asarray(y)

        n_samples, n_features = X.shape

        self.weights = np.zeros(n_features)
        self.bias = 0.0

        for epoch in range(self.n_iter):

            for idx, x_i in enumerate(X):

                z = np.dot(x_i, self.weights) + self.bias

                y_pred = Sigmoid(z)

                error = y_pred - y[idx]

                gradient = error * Sigmoid_derivative(z)

                self.weights -= self.lr * gradient * x_i
                self.bias -= self.lr * gradient

            if (epoch + 1) % 10 == 0:
                print(f"Epoch {epoch+1}/{self.n_iter} "f"Loss={np.mean((self.predict_proba(X)-y)**2):.4f}" )

    def predict_proba(self, X):

        X = np.asarray(X, dtype=np.float64)

        z = np.dot(X, self.weights) + self.bias

        return Sigmoid(z)

    def predict(self, X):

        probs = self.predict_proba(X)

        return (probs >= 0.5).astype(int)

In [5]:
df = pd.read_csv("/content/Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df = df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [7]:
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
df['Embarked'] = df['Embarked'].map({'S': 0, 'C': 1, 'Q': 2})
df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    0  22.0      1      0   7.2500       0.0
1         1       1    1  38.0      1      0  71.2833       1.0
2         1       3    1  26.0      0      0   7.9250       0.0
3         1       1    1  35.0      1      0  53.1000       0.0
4         0       3    0  35.0      0      0   8.0500       0.0

In [8]:
df.fillna(df.mean(), inplace=True)
df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    0  22.0      1      0   7.2500       0.0
1         1       1    1  38.0      1      0  71.2833       1.0
2         1       3    1  26.0      0      0   7.9250       0.0
3         1       1    1  35.0      1      0  53.1000       0.0
4         0       3    0  35.0      0      0   8.0500       0.0

In [9]:
x = df.drop('Survived', axis=1)
y = df['Survived']

In [10]:
import sklearn.model_selection as model_selection

x_train, x_test, y_train, y_test = model_selection.train_test_split(x, y, test_size=0.2)

In [11]:


p = Perceptron(
    learning_rate=0.01,
    n_iter=100
)

p.fit(x_train, y_train)

Epoch 10/100 Loss=0.3048
Epoch 20/100 Loss=0.3079
Epoch 30/100 Loss=0.3047
Epoch 40/100 Loss=0.2962
Epoch 50/100 Loss=0.2818
Epoch 60/100 Loss=0.2697
Epoch 70/100 Loss=0.2506
Epoch 80/100 Loss=0.2455
Epoch 90/100 Loss=0.2428
Epoch 100/100 Loss=0.2398

In [12]:
preds=p.predict(x_test)

In [13]:
acc = accuracy_score(y_test, preds)
acc

0.7150837988826816